### ISSUE TITLE
Increase max_length: bot_token and chat_id 

### ISSUE THREAD

**Issue by rogersdepelle** [thela/django_log_to_telegram#1]
Telegram has created bot tokens longer than 45 (I have already been generated one of 47) and chat ids greater than 8.

Thanks for creating this package, I like it a lot :-)

**Comment by thela** [comment]
First of all, thanks to you for using it, I'm very glad you find it useful.

I checked in the [Telegram Api](https://core.telegram.org/bots/api#chat), it says that a chat id will always be smaller than 52 bits, so 16 chars should suffice.

As for the bot token, I really couldn't find any reference of its length, I made it 50 chars for now, I'll look into it.

**Comment by rogersdepelle** [comment]
Thanks for fix it!
